#!/usr/bin/env python
import json
import pathlib
import sys

import conda.cli.python_api as conda_cli


def latest_conda_packages(channel):
    stdout, _, _ = conda_cli.run_command(conda_cli.Commands.SEARCH, ['--override-channels', '--channel', channel, '--json'])
    for k, v in json.loads(stdout).items():
        vs = sorted(p['version'] for p in v)
        yield k, vs[-1]

notebooks = pathlib.Path('.').glob('**/*.ipynb')
packages_versions = dict(latest_conda_packages(channel='litex-hub'))

for n in notebooks:
    with open(n, 'r') as f:
        data = json.load(f)
        for c in data['cells']:
            for i, l in enumerate(c['source']):
                for p, v in packages_versions.items():
                    # [parent_package].sub_package
                    var = p.split('.')[0].replace('-', '_') + '_version'
                    # [semver_builno]_grev
                    ver = v.split('_g')[0]
                    if l.startswith(f'{var} = '):
                        print(f'{n}: bumping {var} to "{ver}"', file=sys.stderr)
                        c['source'][i] = f'''{var} = '{ver}' #@param {{type:"string"}}'''

    with open(n, 'w') as f:
        json.dump(data, f, indent=2)
